# Site
name: "BlogTrial"
title: "BlogTrial"
description: "Jekyll template, Medium styled, for BlogTrial."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
